### ISSUE TITLE
Airqo Devices' latitude and longitude values

### ISSUE THREAD

**Issue by NoahNsimbe** [airqo-platform/AirQo-api#338]
**What were you trying to achieve?**
Get Airqo devices' latitude and longitude values using the staging endpoint

**What are the expected results?**
Expected all devices to have latitude and longitude values

**What are the received results?**
Some devices didn't have latitude and longitude values

**What are the steps to reproduce the issue?**
When you get the Airqo devices using the staging URL, some devices don't have latitude and longitude values, but the latitude and longitude values are returned when you use the production URL for the same devices

**In what environment did you encounter the issue?**

**Additional context**
The staging DB doesn't look to be up-to-date

**Comment by Baalmart** [comment]
Thanks @NoahNsimbe , the staging endpoint is ideally for system tests so it is expected to misalign with the values of the production environment.

Actually, we might want to reduce the frequency at which we update the staging DB for the **Events collection** since it is just for test purposes. By "reducing frequency": in case we were updating every 3 mins, we could now just update every after 12 hours for the staging Events collection.
